<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Error 404 |PFE</title>
    <link rel="stylesheet" href="./vendor/css/error.css" />
  </head>
  <body>
    <div class="container">
      <div class="num-erro"><p>404</p></div>
      <div class="ops-msg"><p>OPPS !</p></div>
      <div class="ops-descr">
        <p>EROOR C'est produit</p>
        <p>
          Vous n'avez pas l'autorisation d'acces a cette page on va vous redirecter vers la page de la connection merci de renouvler la connection!
        </p>
      </div>
    </div>
    <script src="vendor/script/error.js"></script>
  </body>
</html>
